name: "Apply Record manifests to Cloudflare"

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
  - cron: "*/5 * * * *"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq
          sudo pip install yq
      - run: |
          chmod +x ./scripts/validate_manifests.sh
          ./scripts/validate_manifests.sh
  build:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq
          sudo pip install yq
      - run: |
          chmod +x ./scripts/apply_records.sh
          ./scripts/apply_records.sh \
            "${{ secrets.CF_TOKEN }}" \
            "sunrin.io=${{ secrets.CF_ZONE_SUNRIN_IO }}" \
            "swfestival.kr=${{ secrets.CF_ZONE_SWFESTIVAL_KR }}"
